// Generated from outputs/import-preview.json by scripts/generate-trail-data.mjs.
// The source snapshot passed validation on 14 August 2026.

export type CyprusE4Stage = {
  id: string;
  sequence: number;
  name: string;
  distanceFromPathKm: number | null;
  accumulatedDistanceKm: number | null;
  segmentLengthKm: number | null;
  elevationUpM: number | null;
  elevationDownM: number | null;
  altitudeM: number | null;
  services: Record<string, boolean>;
};

export const cyprusE4 = {
  "id": "cyprus-e4",
  "name": "Cyprus E4",
  "country": "Cyprus",
  "distanceKm": 558.091042780747,
  "stageCount": 123,
  "highPointM": 1732.0009266133,
  "startStageName": "Pafos Airport",
  "endStageName": "Larnaka Airport",
  "dataUpdatedAt": "2026-08-07T13:15:48Z"
} as const;

export const cyprusE4Stages: CyprusE4Stage[] = [
  {
    "id": "123-pafos-airport",
    "sequence": 123,
    "name": "Pafos Airport",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 0,
    "segmentLengthKm": 0,
    "elevationUpM": 0,
    "elevationDownM": 0,
    "altitudeM": 2,
    "services": {
      "lodging": true,
      "tent": true,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "122-acheleia",
    "sequence": 122,
    "name": "Acheleia",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 6.27,
    "segmentLengthKm": 6.27,
    "elevationUpM": 52,
    "elevationDownM": 15,
    "altitudeM": 39,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "121-agia-varvara",
    "sequence": 121,
    "name": "Agia Varvara",
    "distanceFromPathKm": 0.64,
    "accumulatedDistanceKm": 9.459999999999999,
    "segmentLengthKm": 3.19,
    "elevationUpM": 37,
    "elevationDownM": 11,
    "altitudeM": 65,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "120-episkopi-pafou",
    "sequence": 120,
    "name": "Episkopi Pafou",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 16,
    "segmentLengthKm": 6.54,
    "elevationUpM": 223,
    "elevationDownM": 90,
    "altitudeM": 198,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "119-ezousa-picnic-site",
    "sequence": 119,
    "name": "Ezousa Picnic Site",
    "distanceFromPathKm": 0.91,
    "accumulatedDistanceKm": 17.47,
    "segmentLengthKm": 1.47,
    "elevationUpM": 41,
    "elevationDownM": 27,
    "altitudeM": 212,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "118-moro-nero",
    "sequence": 118,
    "name": "Moro Nero",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 18.52,
    "segmentLengthKm": 1.05,
    "elevationUpM": 72,
    "elevationDownM": 37,
    "altitudeM": 247,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "117-minthis",
    "sequence": 117,
    "name": "Minthis",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 23.18,
    "segmentLengthKm": 4.66,
    "elevationUpM": 349,
    "elevationDownM": 81,
    "altitudeM": 515,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "116-tsada",
    "sequence": 116,
    "name": "Tsada",
    "distanceFromPathKm": 0.46,
    "accumulatedDistanceKm": 25.95,
    "segmentLengthKm": 2.77,
    "elevationUpM": 108,
    "elevationDownM": 40,
    "altitudeM": 583,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "115-koili",
    "sequence": 115,
    "name": "Koili",
    "distanceFromPathKm": 0.4,
    "accumulatedDistanceKm": 34.92,
    "segmentLengthKm": 8.97,
    "elevationUpM": 346,
    "elevationDownM": 302,
    "altitudeM": 627,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "114-baths-of-adonis",
    "sequence": 114,
    "name": "Baths of Adonis",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 38.120000000000005,
    "segmentLengthKm": 3.2,
    "elevationUpM": 22,
    "elevationDownM": 364,
    "altitudeM": 285,
    "services": {
      "lodging": true,
      "tent": true,
      "food": false,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "113-pegeia",
    "sequence": 113,
    "name": "Pegeia",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 48.13,
    "segmentLengthKm": 10.01,
    "elevationUpM": 298,
    "elevationDownM": 375,
    "altitudeM": 208,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "112-pikni-forest-picnic-site",
    "sequence": 112,
    "name": "Pikni Forest picnic site",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 51.81,
    "segmentLengthKm": 3.68,
    "elevationUpM": 279,
    "elevationDownM": 106,
    "altitudeM": 381,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "111-pafos-zoo",
    "sequence": 111,
    "name": "Pafos Zoo",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 55.38,
    "segmentLengthKm": 3.57,
    "elevationUpM": 10,
    "elevationDownM": 271,
    "altitudeM": 120,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": true,
      "busStop": false
    }
  },
  {
    "id": "110-agios-georgios-pegeias",
    "sequence": 110,
    "name": "Agios Georgios Pegeias",
    "distanceFromPathKm": 1.28,
    "accumulatedDistanceKm": 57.07,
    "segmentLengthKm": 1.69,
    "elevationUpM": 4,
    "elevationDownM": 53,
    "altitudeM": 71,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "109-agia-matrona-i-rossida",
    "sequence": 109,
    "name": "Agia Matrona I Rossida",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 58.33,
    "segmentLengthKm": 1.26,
    "elevationUpM": 11,
    "elevationDownM": 25,
    "altitudeM": 57,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "108-avakas-gorge",
    "sequence": 108,
    "name": "Avakas Gorge",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 59.61,
    "segmentLengthKm": 1.28,
    "elevationUpM": 25,
    "elevationDownM": 47,
    "altitudeM": 35,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "107-lara-beach",
    "sequence": 107,
    "name": "Lara Beach",
    "distanceFromPathKm": 0.56,
    "accumulatedDistanceKm": 64.16,
    "segmentLengthKm": 4.55,
    "elevationUpM": 40,
    "elevationDownM": 49,
    "altitudeM": 26,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "106-akamas-water-fountain",
    "sequence": 106,
    "name": "Akamas Water Fountain",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 72.69,
    "segmentLengthKm": 8.53,
    "elevationUpM": 127,
    "elevationDownM": 126,
    "altitudeM": 27,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "105-fontana-amorosa",
    "sequence": 105,
    "name": "Fontana Amorosa",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 86.59,
    "segmentLengthKm": 13.9,
    "elevationUpM": 217,
    "elevationDownM": 234,
    "altitudeM": 10,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "104-baths-of-aphrodite",
    "sequence": 104,
    "name": "Baths of Aphrodite",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 92.45,
    "segmentLengthKm": 5.86,
    "elevationUpM": 136,
    "elevationDownM": 98,
    "altitudeM": 48,
    "services": {
      "lodging": true,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "103-kefalovrisia-spring",
    "sequence": 103,
    "name": "Kefalovrisia Spring",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 96.07000000000001,
    "segmentLengthKm": 3.62,
    "elevationUpM": 272,
    "elevationDownM": 27,
    "altitudeM": 293,
    "services": {
      "lodging": true,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "102-aphrodites-and-adonis-oak",
    "sequence": 102,
    "name": "Aphrodites and Adonis Oak",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 97.62,
    "segmentLengthKm": 1.55,
    "elevationUpM": 52,
    "elevationDownM": 85,
    "altitudeM": 260,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "101-moutti-tis-sotiras-excursion",
    "sequence": 101,
    "name": "Moutti tis Sotiras Excursion",
    "distanceFromPathKm": 0.7,
    "accumulatedDistanceKm": 98.01,
    "segmentLengthKm": 0.39,
    "elevationUpM": 26,
    "elevationDownM": 0,
    "altitudeM": 286,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "100-smigies-picnic-site",
    "sequence": 100,
    "name": "Smigies Picnic site",
    "distanceFromPathKm": 0.4,
    "accumulatedDistanceKm": 103.61,
    "segmentLengthKm": 5.6,
    "elevationUpM": 191,
    "elevationDownM": 160,
    "altitudeM": 317,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "99-drousia-picnic-area",
    "sequence": 99,
    "name": "Drousia Picnic Area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 111.97,
    "segmentLengthKm": 8.36,
    "elevationUpM": 369,
    "elevationDownM": 118,
    "altitudeM": 568,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "98-chruch-of-st-luke",
    "sequence": 98,
    "name": "Chruch of St. Luke",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 113.35,
    "segmentLengthKm": 1.38,
    "elevationUpM": 53,
    "elevationDownM": 3,
    "altitudeM": 618,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "97-drouseia-ineia",
    "sequence": 97,
    "name": "Drouseia/Ineia",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 115.39,
    "segmentLengthKm": 2.04,
    "elevationUpM": 65,
    "elevationDownM": 52,
    "altitudeM": 631,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "96-kritou-terra",
    "sequence": 96,
    "name": "Kritou Terra",
    "distanceFromPathKm": 0.35,
    "accumulatedDistanceKm": 118.64,
    "segmentLengthKm": 3.25,
    "elevationUpM": 6,
    "elevationDownM": 162,
    "altitudeM": 475,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "95-terra",
    "sequence": 95,
    "name": "Terra",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 119.93,
    "segmentLengthKm": 1.29,
    "elevationUpM": 5,
    "elevationDownM": 71,
    "altitudeM": 409,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "94-chrysochous-fountain",
    "sequence": 94,
    "name": "Chrysochous Fountain",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 123.55000000000001,
    "segmentLengthKm": 3.62,
    "elevationUpM": 11,
    "elevationDownM": 184,
    "altitudeM": 236,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "93-chrysochous",
    "sequence": 93,
    "name": "Chrysochous",
    "distanceFromPathKm": 0.82,
    "accumulatedDistanceKm": 125.91000000000001,
    "segmentLengthKm": 2.36,
    "elevationUpM": 23,
    "elevationDownM": 173,
    "altitudeM": 86,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "92-goudi",
    "sequence": 92,
    "name": "Goudi",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 126.89000000000001,
    "segmentLengthKm": 0.98,
    "elevationUpM": 19,
    "elevationDownM": 8,
    "altitudeM": 97,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "91-agios-isidorous",
    "sequence": 91,
    "name": "Agios Isidorous",
    "distanceFromPathKm": 0.38,
    "accumulatedDistanceKm": 130.14000000000001,
    "segmentLengthKm": 3.25,
    "elevationUpM": 148,
    "elevationDownM": 65,
    "altitudeM": 180,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "90-steni",
    "sequence": 90,
    "name": "Steni",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 130.65,
    "segmentLengthKm": 0.51,
    "elevationUpM": 7,
    "elevationDownM": 13,
    "altitudeM": 174,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "89-monastery-of-virgin-mary-xrisolakourna",
    "sequence": 89,
    "name": "Monastery of Virgin Mary Xrisolakourna",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 132.8,
    "segmentLengthKm": 2.15,
    "elevationUpM": 197,
    "elevationDownM": 2,
    "altitudeM": 369,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "88-lysos",
    "sequence": 88,
    "name": "Lysos",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 138.87,
    "segmentLengthKm": 6.07,
    "elevationUpM": 323,
    "elevationDownM": 122,
    "altitudeM": 570,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "87-melandra",
    "sequence": 87,
    "name": "Melandra",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 140.82,
    "segmentLengthKm": 1.95,
    "elevationUpM": 77,
    "elevationDownM": 70,
    "altitudeM": 577,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "86-evagoras-pallikarides-monument",
    "sequence": 86,
    "name": "Evagoras Pallikarides Monument",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 142.91,
    "segmentLengthKm": 2.09,
    "elevationUpM": 44,
    "elevationDownM": 112,
    "altitudeM": 509,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "85-junction-spring",
    "sequence": 85,
    "name": "Junction Spring",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 150.01,
    "segmentLengthKm": 7.1,
    "elevationUpM": 407,
    "elevationDownM": 449,
    "altitudeM": 467,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "84-stavros-tis-psokas",
    "sequence": 84,
    "name": "Stavros tis Psokas",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 164.16,
    "segmentLengthKm": 14.15,
    "elevationUpM": 836,
    "elevationDownM": 500,
    "altitudeM": 803,
    "services": {
      "lodging": true,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "83-tripylos-fire-look-out",
    "sequence": 83,
    "name": "Tripylos Fire Look out",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 175.31,
    "segmentLengthKm": 11.15,
    "elevationUpM": 911,
    "elevationDownM": 351,
    "altitudeM": 1363,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "82-cedar-valley",
    "sequence": 82,
    "name": "Cedar Valley",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 178.19,
    "segmentLengthKm": 2.88,
    "elevationUpM": 157,
    "elevationDownM": 388,
    "altitudeM": 1132,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "81-kykkos-monastery",
    "sequence": 81,
    "name": "Kykkos Monastery",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 206.29,
    "segmentLengthKm": 28.1,
    "elevationUpM": 2576,
    "elevationDownM": 2630,
    "altitudeM": 1078,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "80-milikouri",
    "sequence": 80,
    "name": "Milikouri",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 209.87,
    "segmentLengthKm": 3.58,
    "elevationUpM": 300,
    "elevationDownM": 513,
    "altitudeM": 865,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "79-komijii-picnic-area",
    "sequence": 79,
    "name": "Komijii picnic area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 214.97,
    "segmentLengthKm": 5.1,
    "elevationUpM": 293,
    "elevationDownM": 487,
    "altitudeM": 671,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "78-spring",
    "sequence": 78,
    "name": "Spring",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 218.51,
    "segmentLengthKm": 3.54,
    "elevationUpM": 235,
    "elevationDownM": 145,
    "altitudeM": 761,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "77-kaminaria",
    "sequence": 77,
    "name": "Kaminaria",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 222.73,
    "segmentLengthKm": 4.22,
    "elevationUpM": 322,
    "elevationDownM": 328,
    "altitudeM": 755,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "76-treis-elies",
    "sequence": 76,
    "name": "Treis Elies",
    "distanceFromPathKm": 1.9,
    "accumulatedDistanceKm": 222.73,
    "segmentLengthKm": 0,
    "elevationUpM": 0,
    "elevationDownM": 0,
    "altitudeM": 0,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "75-agios-georgios-kapourallis",
    "sequence": 75,
    "name": "Agios Georgios Kapourallis",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 231.7,
    "segmentLengthKm": 8.97,
    "elevationUpM": 898,
    "elevationDownM": 623,
    "altitudeM": 1030,
    "services": {
      "lodging": true,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "74-kampoi-tou-kalogyrou",
    "sequence": 74,
    "name": "Kampoi tou Kalogyrou",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 235.76999999999998,
    "segmentLengthKm": 4.07,
    "elevationUpM": 472,
    "elevationDownM": 181,
    "altitudeM": 1321,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "73-trooditissa-monastery",
    "sequence": 73,
    "name": "Trooditissa Monastery",
    "distanceFromPathKm": 1.94,
    "accumulatedDistanceKm": 237.58999999999997,
    "segmentLengthKm": 1.82,
    "elevationUpM": 183,
    "elevationDownM": 27,
    "altitudeM": 1477,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "72-pano-platres",
    "sequence": 72,
    "name": "Pano Platres",
    "distanceFromPathKm": 2.5,
    "accumulatedDistanceKm": 243.18999999999997,
    "segmentLengthKm": 5.6,
    "elevationUpM": 263,
    "elevationDownM": 434,
    "altitudeM": 1306,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": true,
      "toilets": true,
      "medical": true,
      "pharmacy": false,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "71-persephoni-trail-viewpoint-excursion",
    "sequence": 71,
    "name": "Persephoni trail viewpoint Excursion",
    "distanceFromPathKm": 0.63,
    "accumulatedDistanceKm": 249.66999999999996,
    "segmentLengthKm": 6.48,
    "elevationUpM": 563,
    "elevationDownM": 208,
    "altitudeM": 1661,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "70-troodos",
    "sequence": 70,
    "name": "Troodos",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 252.56999999999996,
    "segmentLengthKm": 2.9,
    "elevationUpM": 109,
    "elevationDownM": 49,
    "altitudeM": 1721,
    "services": {
      "lodging": true,
      "tent": true,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "69-platania-karvounas",
    "sequence": 69,
    "name": "Platania/Karvounas",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 262.30999999999995,
    "segmentLengthKm": 9.74,
    "elevationUpM": 290,
    "elevationDownM": 882,
    "altitudeM": 1129,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": true,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "68-kiperounta-outskirts",
    "sequence": 68,
    "name": "Kiperounta outskirts",
    "distanceFromPathKm": 0.75,
    "accumulatedDistanceKm": 265.91999999999996,
    "segmentLengthKm": 3.61,
    "elevationUpM": 332,
    "elevationDownM": 220,
    "altitudeM": 1241,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": true,
      "pharmacy": false,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "67-adventure-mountain-park",
    "sequence": 67,
    "name": "Adventure Mountain Park",
    "distanceFromPathKm": 0.25,
    "accumulatedDistanceKm": 268.29999999999995,
    "segmentLengthKm": 2.38,
    "elevationUpM": 111,
    "elevationDownM": 29,
    "altitudeM": 1323,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "66-spilia",
    "sequence": 66,
    "name": "Spilia",
    "distanceFromPathKm": 1.09,
    "accumulatedDistanceKm": 269.99999999999994,
    "segmentLengthKm": 1.7,
    "elevationUpM": 8,
    "elevationDownM": 172,
    "altitudeM": 1159,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "65-saranti",
    "sequence": 65,
    "name": "Saranti",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 275.65999999999997,
    "segmentLengthKm": 5.66,
    "elevationUpM": 439,
    "elevationDownM": 541,
    "altitudeM": 1057,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "64-monastery-panagia-tou-araka",
    "sequence": 64,
    "name": "Monastery Panagia tou Araka",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 276.49999999999994,
    "segmentLengthKm": 0.84,
    "elevationUpM": 30,
    "elevationDownM": 34,
    "altitudeM": 1053,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "63-lagoudera-picnic-site",
    "sequence": 63,
    "name": "Lagoudera picnic site",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 277.16999999999996,
    "segmentLengthKm": 0.67,
    "elevationUpM": 42,
    "elevationDownM": 52,
    "altitudeM": 1043,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "62-stavros-agiasmati-church",
    "sequence": 62,
    "name": "Stavros Agiasmati Church",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 283.43999999999994,
    "segmentLengthKm": 6.27,
    "elevationUpM": 484,
    "elevationDownM": 654,
    "altitudeM": 873,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "61-gefyri-tis-panagias-picnic-site",
    "sequence": 61,
    "name": "Gefyri tis Panagias picnic site",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 292.42999999999995,
    "segmentLengthKm": 8.99,
    "elevationUpM": 409,
    "elevationDownM": 828,
    "altitudeM": 454,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "60-agios-epifanios",
    "sequence": 60,
    "name": "Agios Epifanios",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 299.18999999999994,
    "segmentLengthKm": 6.76,
    "elevationUpM": 240,
    "elevationDownM": 67,
    "altitudeM": 627,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "59-kalo-chorio-orinis",
    "sequence": 59,
    "name": "Kalo Chorio Orinis",
    "distanceFromPathKm": 1.28,
    "accumulatedDistanceKm": 304.85999999999996,
    "segmentLengthKm": 5.67,
    "elevationUpM": 187,
    "elevationDownM": 256,
    "altitudeM": 558,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "58-kalo-xorio-orinis-picnic-site",
    "sequence": 58,
    "name": "Kalo Xorio Orinis picnic site",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 305.48999999999995,
    "segmentLengthKm": 0.63,
    "elevationUpM": 13,
    "elevationDownM": 24,
    "altitudeM": 547,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "57-fikardou-gourri",
    "sequence": 57,
    "name": "Fikardou/Gourri",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 310.78,
    "segmentLengthKm": 5.29,
    "elevationUpM": 418,
    "elevationDownM": 89,
    "altitudeM": 876,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "56-lazanias",
    "sequence": 56,
    "name": "Lazanias",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 313.28,
    "segmentLengthKm": 2.5,
    "elevationUpM": 248,
    "elevationDownM": 228,
    "altitudeM": 896,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "55-machairas-monastery",
    "sequence": 55,
    "name": "Machairas Monastery",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 315.89,
    "segmentLengthKm": 2.61,
    "elevationUpM": 150,
    "elevationDownM": 145,
    "altitudeM": 901,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "54-kionia-picnic-area",
    "sequence": 54,
    "name": "Kionia Picnic Area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 321.25,
    "segmentLengthKm": 5.36,
    "elevationUpM": 644,
    "elevationDownM": 319,
    "altitudeM": 1226,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "53-prophet-ilias-monastery",
    "sequence": 53,
    "name": "Prophet Ilias Monastery",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 328.57,
    "segmentLengthKm": 7.32,
    "elevationUpM": 185,
    "elevationDownM": 734,
    "altitudeM": 677,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "52-lithrodontas",
    "sequence": 52,
    "name": "Lithrodontas",
    "distanceFromPathKm": 0.73,
    "accumulatedDistanceKm": 336.93,
    "segmentLengthKm": 8.36,
    "elevationUpM": 242,
    "elevationDownM": 489,
    "altitudeM": 430,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "51-delikipos",
    "sequence": 51,
    "name": "Delikipos",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 349.57,
    "segmentLengthKm": 12.64,
    "elevationUpM": 500,
    "elevationDownM": 638,
    "altitudeM": 292,
    "services": {
      "lodging": false,
      "tent": true,
      "food": true,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "50-kornos",
    "sequence": 50,
    "name": "Kornos",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 354.36,
    "segmentLengthKm": 4.79,
    "elevationUpM": 90,
    "elevationDownM": 62,
    "altitudeM": 320,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "49-kornos-picnic-site",
    "sequence": 49,
    "name": "Kornos picnic site",
    "distanceFromPathKm": 0.9,
    "accumulatedDistanceKm": 355.51,
    "segmentLengthKm": 1.15,
    "elevationUpM": 18,
    "elevationDownM": 3,
    "altitudeM": 335,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "48-stavrovouni-monastery",
    "sequence": 48,
    "name": "Stavrovouni Monastery",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 363.25,
    "segmentLengthKm": 7.74,
    "elevationUpM": 411,
    "elevationDownM": 110,
    "altitudeM": 636,
    "services": {
      "lodging": true,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "47-holy-monastery-agia-varvara",
    "sequence": 47,
    "name": "Holy Monastery Agia Varvara",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 365.86,
    "segmentLengthKm": 2.61,
    "elevationUpM": 15,
    "elevationDownM": 329,
    "altitudeM": 322,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "46-pyrga",
    "sequence": 46,
    "name": "Pyrga",
    "distanceFromPathKm": 1.82,
    "accumulatedDistanceKm": 371.28000000000003,
    "segmentLengthKm": 5.42,
    "elevationUpM": 69,
    "elevationDownM": 157,
    "altitudeM": 234,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "45-panagia-stazousa",
    "sequence": 45,
    "name": "Panagia Stazousa",
    "distanceFromPathKm": 0.72,
    "accumulatedDistanceKm": 375.07000000000005,
    "segmentLengthKm": 3.79,
    "elevationUpM": 72,
    "elevationDownM": 114,
    "altitudeM": 192,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "44-klavdia",
    "sequence": 44,
    "name": "Klavdia",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 378.81000000000006,
    "segmentLengthKm": 3.74,
    "elevationUpM": 26,
    "elevationDownM": 113,
    "altitudeM": 105,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "43-kalo-chorio-larnakas",
    "sequence": 43,
    "name": "Kalo Chorio Larnakas",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 384.59000000000003,
    "segmentLengthKm": 5.78,
    "elevationUpM": 38,
    "elevationDownM": 65,
    "altitudeM": 78,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "42-kosi",
    "sequence": 42,
    "name": "Kosi",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 396.06000000000006,
    "segmentLengthKm": 11.47,
    "elevationUpM": 330,
    "elevationDownM": 240,
    "altitudeM": 168,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "41-archangel-michael-rest-area",
    "sequence": 41,
    "name": "Archangel Michael rest area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 400.06000000000006,
    "segmentLengthKm": 4,
    "elevationUpM": 71,
    "elevationDownM": 55,
    "altitudeM": 184,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "40-avdellero",
    "sequence": 40,
    "name": "Avdellero",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 405.6700000000001,
    "segmentLengthKm": 5.61,
    "elevationUpM": 71,
    "elevationDownM": 125,
    "altitudeM": 130,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": true,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "39-iera-moni-metamorfoseos-tou-sotiros-xristou-excursion",
    "sequence": 39,
    "name": "Iera Moni Metamorfoseos tou Sotiros Xristou Excursion",
    "distanceFromPathKm": 1,
    "accumulatedDistanceKm": 407.1400000000001,
    "segmentLengthKm": 1.47,
    "elevationUpM": 22,
    "elevationDownM": 11,
    "altitudeM": 141,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "38-iera-moni-panagias-rodon-to-amaranton",
    "sequence": 38,
    "name": "Iera Moni Panagias Rodon to Amaranton",
    "distanceFromPathKm": 0.22,
    "accumulatedDistanceKm": 410.2300000000001,
    "segmentLengthKm": 3.09,
    "elevationUpM": 17,
    "elevationDownM": 51,
    "altitudeM": 107,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "37-troulloi",
    "sequence": 37,
    "name": "Troulloi",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 411.2800000000001,
    "segmentLengthKm": 1.05,
    "elevationUpM": 7,
    "elevationDownM": 2,
    "altitudeM": 112,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "36-ekdormikos-xoros-troullon",
    "sequence": 36,
    "name": "Ekdormikos Xoros Troullon",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 415.1000000000001,
    "segmentLengthKm": 3.82,
    "elevationUpM": 19,
    "elevationDownM": 43,
    "altitudeM": 88,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "35-monastery-st-george-mavrovouniou",
    "sequence": 35,
    "name": "Monastery St George Mavrovouniou",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 416.13000000000005,
    "segmentLengthKm": 1.03,
    "elevationUpM": 0,
    "elevationDownM": 16,
    "altitudeM": 72,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "34-aspromoutti-forest",
    "sequence": 34,
    "name": "Aspromoutti Forest",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 422.66,
    "segmentLengthKm": 6.53,
    "elevationUpM": 171,
    "elevationDownM": 152,
    "altitudeM": 91,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "33-pyla-n",
    "sequence": 33,
    "name": "Pyla N",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 425.12,
    "segmentLengthKm": 2.46,
    "elevationUpM": 23,
    "elevationDownM": 56,
    "altitudeM": 58,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "32-kingsfield-airfield",
    "sequence": 32,
    "name": "Kingsfield Airfield",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 427.41,
    "segmentLengthKm": 2.29,
    "elevationUpM": 60,
    "elevationDownM": 26,
    "altitudeM": 92,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "31-xylotymbou",
    "sequence": 31,
    "name": "Xylotymbou",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 429.90000000000003,
    "segmentLengthKm": 2.49,
    "elevationUpM": 0,
    "elevationDownM": 27,
    "altitudeM": 65,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "30-dasaki-axnas",
    "sequence": 30,
    "name": "Dasaki Axnas",
    "distanceFromPathKm": 2.05,
    "accumulatedDistanceKm": 433.76000000000005,
    "segmentLengthKm": 3.86,
    "elevationUpM": 15,
    "elevationDownM": 27,
    "altitudeM": 53,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "29-ormideia",
    "sequence": 29,
    "name": "Ormideia",
    "distanceFromPathKm": 1.45,
    "accumulatedDistanceKm": 434.9800000000001,
    "segmentLengthKm": 1.22,
    "elevationUpM": 5,
    "elevationDownM": 5,
    "altitudeM": 53,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "28-church-of-st-george-of-agkonas",
    "sequence": 28,
    "name": "Church of St George of Agkonas",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 437.0200000000001,
    "segmentLengthKm": 2.04,
    "elevationUpM": 4,
    "elevationDownM": 1,
    "altitudeM": 56,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "27-xylofagou-n",
    "sequence": 27,
    "name": "Xylofagou N",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 444.05000000000007,
    "segmentLengthKm": 7.03,
    "elevationUpM": 15,
    "elevationDownM": 19,
    "altitudeM": 52,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "26-liopetri",
    "sequence": 26,
    "name": "Liopetri",
    "distanceFromPathKm": 1.09,
    "accumulatedDistanceKm": 450.56000000000006,
    "segmentLengthKm": 6.51,
    "elevationUpM": 19,
    "elevationDownM": 36,
    "altitudeM": 35,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "25-sotira",
    "sequence": 25,
    "name": "Sotira",
    "distanceFromPathKm": 2.2,
    "accumulatedDistanceKm": 457.9100000000001,
    "segmentLengthKm": 7.35,
    "elevationUpM": 58,
    "elevationDownM": 19,
    "altitudeM": 74,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "24-agios-antonios-picnic-area",
    "sequence": 24,
    "name": "Agios Antonios picnic area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 459.2800000000001,
    "segmentLengthKm": 1.37,
    "elevationUpM": 26,
    "elevationDownM": 0,
    "altitudeM": 100,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "23-agia-napa-n",
    "sequence": 23,
    "name": "Agia Napa N",
    "distanceFromPathKm": 0.6,
    "accumulatedDistanceKm": 464.7300000000001,
    "segmentLengthKm": 5.45,
    "elevationUpM": 78,
    "elevationDownM": 125,
    "altitudeM": 53,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "22-agioi-saranta-cave",
    "sequence": 22,
    "name": "Agioi Saranta Cave",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 468.5900000000001,
    "segmentLengthKm": 3.86,
    "elevationUpM": 116,
    "elevationDownM": 11,
    "altitudeM": 158,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "21-konnos-beach-protaras",
    "sequence": 21,
    "name": "Konnos Beach/Protaras",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 473.9100000000001,
    "segmentLengthKm": 5.32,
    "elevationUpM": 4,
    "elevationDownM": 142,
    "altitudeM": 20,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "20-agioi-anargiroi-picnic-area",
    "sequence": 20,
    "name": "Agioi Anargiroi Picnic Area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 475.5900000000001,
    "segmentLengthKm": 1.68,
    "elevationUpM": 33,
    "elevationDownM": 30,
    "altitudeM": 23,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "19-cape-gkreko",
    "sequence": 19,
    "name": "Cape Gkreko",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 476.7900000000001,
    "segmentLengthKm": 1.2,
    "elevationUpM": 21,
    "elevationDownM": 25,
    "altitudeM": 19,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "18-limnara-beach",
    "sequence": 18,
    "name": "Limnara Beach",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 481.06000000000006,
    "segmentLengthKm": 4.27,
    "elevationUpM": 28,
    "elevationDownM": 44,
    "altitudeM": 3,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "17-agia-napa-s",
    "sequence": 17,
    "name": "Agia Napa S",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 487.02000000000004,
    "segmentLengthKm": 5.96,
    "elevationUpM": 30,
    "elevationDownM": 31,
    "altitudeM": 2,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "16-agia-thekla",
    "sequence": 16,
    "name": "Agia Thekla",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 495.74000000000007,
    "segmentLengthKm": 8.72,
    "elevationUpM": 46,
    "elevationDownM": 39,
    "altitudeM": 9,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "15-xylofagou-s",
    "sequence": 15,
    "name": "Xylofagou S",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 504.39000000000004,
    "segmentLengthKm": 8.65,
    "elevationUpM": 56,
    "elevationDownM": 10,
    "altitudeM": 55,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "14-panagia-evaggelistria-picnic-site",
    "sequence": 14,
    "name": "Panagia Evaggelistria Picnic Site",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 506.6,
    "segmentLengthKm": 2.21,
    "elevationUpM": 18,
    "elevationDownM": 48,
    "altitudeM": 25,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "13-ormideia",
    "sequence": 13,
    "name": "Ormideia",
    "distanceFromPathKm": 2.07,
    "accumulatedDistanceKm": 511.85,
    "segmentLengthKm": 5.25,
    "elevationUpM": 21,
    "elevationDownM": 37,
    "altitudeM": 9,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "12-dhekeleia",
    "sequence": 12,
    "name": "Dhekeleia",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 515.99,
    "segmentLengthKm": 4.14,
    "elevationUpM": 20,
    "elevationDownM": 15,
    "altitudeM": 14,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "11-cto-beach",
    "sequence": 11,
    "name": "CTO Beach",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 519.76,
    "segmentLengthKm": 3.77,
    "elevationUpM": 13,
    "elevationDownM": 17,
    "altitudeM": 10,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "10-pyla-s",
    "sequence": 10,
    "name": "Pyla S",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 524.38,
    "segmentLengthKm": 4.62,
    "elevationUpM": 54,
    "elevationDownM": 3,
    "altitudeM": 61,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "9-oroklini",
    "sequence": 9,
    "name": "Oroklini",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 529.47,
    "segmentLengthKm": 5.09,
    "elevationUpM": 47,
    "elevationDownM": 50,
    "altitudeM": 58,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "8-oroklini-picnic-site",
    "sequence": 8,
    "name": "Oroklini Picnic Site",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 530.75,
    "segmentLengthKm": 1.28,
    "elevationUpM": 56,
    "elevationDownM": 19,
    "altitudeM": 95,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": false
    }
  },
  {
    "id": "7-kellia",
    "sequence": 7,
    "name": "Kellia",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 533.78,
    "segmentLengthKm": 3.03,
    "elevationUpM": 36,
    "elevationDownM": 87,
    "altitudeM": 44,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "6-panagia-aimatousa",
    "sequence": 6,
    "name": "Panagia Aimatousa",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 540.72,
    "segmentLengthKm": 6.94,
    "elevationUpM": 93,
    "elevationDownM": 50,
    "altitudeM": 87,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "5-rizoelia-park",
    "sequence": 5,
    "name": "Rizoelia Park",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 543.9100000000001,
    "segmentLengthKm": 3.19,
    "elevationUpM": 55,
    "elevationDownM": 37,
    "altitudeM": 105,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "4-larnaka",
    "sequence": 4,
    "name": "Larnaka",
    "distanceFromPathKm": 2,
    "accumulatedDistanceKm": 550.69,
    "segmentLengthKm": 6.78,
    "elevationUpM": 42,
    "elevationDownM": 127,
    "altitudeM": 20,
    "services": {
      "lodging": true,
      "tent": false,
      "food": true,
      "grocery": true,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": false,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  },
  {
    "id": "3-hala-sultan-tekke",
    "sequence": 3,
    "name": "Hala Sultan Tekke",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 554.5,
    "segmentLengthKm": 3.81,
    "elevationUpM": 26,
    "elevationDownM": 32,
    "altitudeM": 14,
    "services": {
      "lodging": false,
      "tent": false,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "2-tekke-picnic-area",
    "sequence": 2,
    "name": "Tekke picnic area",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 555.6,
    "segmentLengthKm": 1.1,
    "elevationUpM": 6,
    "elevationDownM": 9,
    "altitudeM": 11,
    "services": {
      "lodging": false,
      "tent": true,
      "food": false,
      "grocery": false,
      "drinkableWater": true,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": false,
      "pharmacy": false,
      "atm": false,
      "busStop": true
    }
  },
  {
    "id": "1-larnaka-airport",
    "sequence": 1,
    "name": "Larnaka Airport",
    "distanceFromPathKm": 0,
    "accumulatedDistanceKm": 557.98,
    "segmentLengthKm": 2.38,
    "elevationUpM": 14,
    "elevationDownM": 5,
    "altitudeM": 20,
    "services": {
      "lodging": false,
      "tent": false,
      "food": true,
      "grocery": false,
      "drinkableWater": false,
      "nonDrinkableWater": false,
      "toilets": true,
      "medical": true,
      "pharmacy": true,
      "atm": true,
      "busStop": true
    }
  }
];

export function getCyprusE4Stage(id: string) {
  return cyprusE4Stages.find((stage) => stage.id === id);
}
