import type { Metadata } from 'next';
import { InformationPage } from '@/components/InformationPage';
import { disableHtmxNavigation } from '@/lib/htmx';

export const metadata: Metadata = { title: 'Help for hikers and hosts', description: 'Planning, offline preparation, account access and accommodation review help from EuroTrex.', alternates: { canonical: '/help' } };

export default function Help() {
  return <InformationPage label="EuroTrex help" title="Find your next step." introduction="Practical answers for exploring a trail, preparing the app, or managing a property.">
    <nav className="help-sections" aria-label="Help topics"><a href="#hikers">For hikers</a><a href="#hosts">For hosts</a><a href="#contact">Contact and corrections</a></nav>
    <section id="hikers"><p className="eyebrow">For hikers</p><h2>Explore first. Prepare before you walk.</h2><details open><summary>What is a stage point?</summary><p>A named reference location along the route—not a prescribed walking day. Distances on the website run from the previous point in the Pafos-to-Larnaka direction. Choose sections around your experience, daylight, water and accommodation.</p></details><details><summary>Can I download the app now?</summary><p>EuroTrex is in private testing. Use Notify me for testing invitations and launch updates. Store availability will be announced when confirmed.</p></details><details><summary>What should I check before going offline?</summary><p>Download the required route information and maps while connected. Check the app’s download status, then test your route without mobile data before leaving. External booking websites, live updates and host contact still need connectivity.</p></details><details><summary>Does an update date mean the trail was checked that day?</summary><p>No. It records a data update. Field-check dates are shown separately when known. Confirm current access, weather, water and services using reliable local sources.</p></details><a className="simple-link" href="/trails/cyprus-e4">Explore Cyprus-E4</a></section>
    <section id="hosts"><p className="eyebrow">For hosts</p><h2>Account approval and listing review are separate.</h2><ol className="help-steps"><li><strong>Create an account and verify your email.</strong> Use your company name and a reachable email address.</li><li><strong>Wait for host access approval.</strong> EuroTrex reviews who you represent before activating your workspace. Return to the portal to check access.</li><li><strong>Prepare and preview a listing.</strong> Drafts autosave. Review the hiker-facing app card before submitting.</li><li><strong>Submit for listing review.</strong> The portal shows the status and any requested changes. Updates do not replace a published listing until approved.</li></ol><p>Account and listing reviews normally take 1–3 days. Contact us if you need help; creating an account does not automatically publish a property.</p><details><summary>I cannot sign in or find the verification email.</summary><p>Check your email spelling and spam folder. Use Forgot password on the sign-in form to request a reset. If signed in but unverified, request a verification email, follow its link, then choose “I have verified my email.”</p></details><details><summary>How do booking and fees work?</summary><p>Hikers contact and book directly with the host. EuroTrex does not process guest payments. Any applicable pilot fees or commission terms are confirmed before publication.</p></details><a className="button button-primary" href="/portal" {...disableHtmxNavigation}>Open Host Portal</a></section>
    <section id="contact"><h2>Tell us what needs attention.</h2><p>For a trail correction, use “Report an issue” on the relevant stage-point page so its context reaches the team. For account help, include what happened but never send passwords or verification codes.</p><a className="button button-secondary" href="/get-involved?interest=other">Contact EuroTrex</a><p>Or email <a className="simple-link" href="mailto:info@eurotrex.eu">info@eurotrex.eu</a>. This is not an emergency service.</p></section>
  </InformationPage>;
}
